name: rlenv
dependencies:
  - python==3.10
  - pip
  - pip:
    - gym==0.26.2
    - torch
    - numpy==1.26.4
    - tensorboardX
    - tensorflow
    - seaborn
    - pettingzoo
    - matplotlib
    - stable_baselines3
    - tqdm
    - patchelf
    - cython<3
    - wandb
